#!/usr/bin/env bash
# setup-tunnel.sh — Configure a named Cloudflare tunnel for Remote Farmer
#
# Named tunnels (vs quick tunnels) provide:
#   - SSE support (fixes r027 blocker — quick tunnels break SSE)
#   - Stable subdomain (no random URLs on each restart)
#   - No 200-request concurrency limit
#   - Cloudflare Access integration for OAuth/OIDC auth layer
#
# Prerequisites:
#   - Cloudflare account (free tier works)
#   - cloudflared CLI installed
#   - A domain managed by Cloudflare DNS (or use .cfargotunnel.com)
#
# Usage:
#   chmod +x setup-tunnel.sh
#   ./setup-tunnel.sh [subdomain] [domain]
#
# Example:
#   ./setup-tunnel.sh farmer example.com
#   -> Creates tunnel "farmer" routing farmer.example.com -> localhost:9090

set -euo pipefail

TUNNEL_NAME="${1:-farmer}"
DOMAIN="${2:-}"
PORT="${3:-9090}"
CONFIG_DIR="${HOME}/.cloudflared"

# --- Color helpers ---
red()   { printf '\033[31m%s\033[0m\n' "$*"; }
green() { printf '\033[32m%s\033[0m\n' "$*"; }
yellow(){ printf '\033[33m%s\033[0m\n' "$*"; }
bold()  { printf '\033[1m%s\033[0m\n' "$*"; }

# --- Step 1: Check cloudflared ---
bold "Step 1: Checking cloudflared installation"
if ! command -v cloudflared &>/dev/null; then
  red "cloudflared not found."
  echo ""
  echo "Install it:"
  echo "  macOS:   brew install cloudflared"
  echo "  Linux:   curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o /usr/local/bin/cloudflared && chmod +x /usr/local/bin/cloudflared"
  echo "  Docker:  docker pull cloudflare/cloudflared"
  echo ""
  echo "Then re-run this script."
  exit 1
fi
green "  cloudflared found: $(cloudflared --version 2>&1 | head -1)"

# --- Step 2: Check authentication ---
bold "Step 2: Checking Cloudflare authentication"
if [ ! -f "${CONFIG_DIR}/cert.pem" ]; then
  yellow "  Not authenticated. Opening browser for Cloudflare login..."
  echo "  This will create ${CONFIG_DIR}/cert.pem"
  echo ""
  cloudflared tunnel login
  if [ ! -f "${CONFIG_DIR}/cert.pem" ]; then
    red "Authentication failed — cert.pem not found after login."
    exit 1
  fi
fi
green "  Authenticated (cert.pem exists)"

# --- Step 3: Create tunnel ---
bold "Step 3: Creating tunnel '${TUNNEL_NAME}'"
# Check if tunnel already exists
if cloudflared tunnel list 2>/dev/null | grep -q "${TUNNEL_NAME}"; then
  yellow "  Tunnel '${TUNNEL_NAME}' already exists — skipping creation"
  TUNNEL_ID=$(cloudflared tunnel list 2>/dev/null | grep "${TUNNEL_NAME}" | awk '{print $1}')
else
  cloudflared tunnel create "${TUNNEL_NAME}"
  TUNNEL_ID=$(cloudflared tunnel list 2>/dev/null | grep "${TUNNEL_NAME}" | awk '{print $1}')
  green "  Created tunnel: ${TUNNEL_ID}"
fi

if [ -z "${TUNNEL_ID}" ]; then
  red "Could not determine tunnel ID. Check 'cloudflared tunnel list'."
  exit 1
fi
green "  Tunnel ID: ${TUNNEL_ID}"

# --- Step 4: DNS routing ---
if [ -n "${DOMAIN}" ]; then
  HOSTNAME="${TUNNEL_NAME}.${DOMAIN}"
  bold "Step 4: Setting up DNS route for ${HOSTNAME}"
  cloudflared tunnel route dns "${TUNNEL_NAME}" "${HOSTNAME}" 2>/dev/null || {
    yellow "  DNS route may already exist — continuing"
  }
  green "  DNS route: ${HOSTNAME} -> tunnel ${TUNNEL_NAME}"
else
  HOSTNAME="${TUNNEL_ID}.cfargotunnel.com"
  bold "Step 4: Skipping DNS (no domain provided)"
  yellow "  Using default: ${HOSTNAME}"
  echo "  To use a custom domain, re-run: ./setup-tunnel.sh ${TUNNEL_NAME} yourdomain.com"
fi

# --- Step 5: Generate config.yml ---
CONFIG_FILE="${CONFIG_DIR}/config.yml"
bold "Step 5: Writing config to ${CONFIG_FILE}"

# Back up existing config if present
if [ -f "${CONFIG_FILE}" ]; then
  cp "${CONFIG_FILE}" "${CONFIG_FILE}.bak"
  yellow "  Backed up existing config to config.yml.bak"
fi

cat > "${CONFIG_FILE}" <<YAML
# Cloudflare named tunnel config for Remote Farmer
# Generated by setup-tunnel.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
#
# Run with: cloudflared tunnel run ${TUNNEL_NAME}
# Or:       cloudflared tunnel --config ${CONFIG_FILE} run ${TUNNEL_NAME}

tunnel: ${TUNNEL_ID}
credentials-file: ${CONFIG_DIR}/${TUNNEL_ID}.json

ingress:
  # WebSocket upgrade handled automatically by cloudflared
  # SSE (text/event-stream) works with named tunnels (not quick tunnels)
  - hostname: ${HOSTNAME}
    service: http://localhost:${PORT}
    originRequest:
      # Keep SSE connections alive — don't timeout long-lived streams
      noTLSVerify: false
      connectTimeout: 30s
      # Named tunnels proxy WebSocket upgrades transparently
      # No special config needed for WS or SSE

  # Catch-all (required by cloudflared)
  - service: http_status:404
YAML

green "  Config written"

# --- Step 6: Summary ---
echo ""
bold "============================================"
bold "  Named tunnel setup complete"
bold "============================================"
echo ""
echo "  Tunnel:    ${TUNNEL_NAME} (${TUNNEL_ID})"
echo "  Hostname:  ${HOSTNAME}"
echo "  Origin:    http://localhost:${PORT}"
echo "  Config:    ${CONFIG_FILE}"
echo "  Creds:     ${CONFIG_DIR}/${TUNNEL_ID}.json"
echo ""
bold "To run:"
echo "  # Terminal 1: Start Farmer server"
echo "  node prototypes/remote-dashboard/server.mjs --port ${PORT} --trust-proxy"
echo ""
echo "  # Terminal 2: Start tunnel"
echo "  cloudflared tunnel run ${TUNNEL_NAME}"
echo ""
echo "  # Open dashboard"
echo "  open https://${HOSTNAME}?token=<your-token>"
echo ""
bold "Optional: Add Cloudflare Access (zero-trust auth layer)"
echo "  1. Go to https://one.dash.cloudflare.com"
echo "  2. Access > Applications > Add an application"
echo "  3. Self-hosted, domain: ${HOSTNAME}"
echo "  4. Add policy: Allow + email in [your@email.com]"
echo "  This adds OAuth/OIDC before the tunnel — double auth with Farmer token."
echo ""
bold "Transport compatibility:"
echo "  Quick tunnel:  WebSocket OK, SSE BROKEN (r027)"
echo "  Named tunnel:  WebSocket OK, SSE OK"
echo "  Both:          HTTP API endpoints work normally"
